version: '3.8'

services:
  n8n:
    build: .
    container_name: n8n
    ports:
      - "10000:10000"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=supersecret
      - N8N_PORT=10000
      - NODE_OPTIONS=--dns-result-order=ipv4first
    volumes:
      - ~/.n8n:/home/node/.n8n
    restart: always
